name: Bleeding edge
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  default:
    uses: cloudposse/github-action-preview-environment-controller/.github/workflows/github-action-bleeding-edge.yml@main
    with:
      organization: "${{ github.event.repository.owner.login }}"
      repository: "${{ github.event.repository.name }}"
      registry: registry.hub.docker.com
    secrets:
      docker-login: "${{ secrets.DOCKERHUB_USERNAME }}"
      docker-password: "${{ secrets.DOCKERHUB_PASSWORD }}"
      github-private-actions-pat: "${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}"