name: Bleeding edge
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  default:
    uses: cloudposse/github-action-preview-environment-controller/.github/workflows/github-action-bleeding-edge.yml@main
