name: Reusable - Bleeding edge
on:
  workflow_call:
    inputs:
      organization:
        required: true
        type: string
      repository:
        required: true
        type: string
    secrets:
      github-private-actions-pat:
        required: true

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: YAML file validation
        uses: mpoc/nexus-validate-using-remote-schema-action@main
        with:
          api-endpoint: https://json.schemastore.org/github-action.json
          yaml-file: action.yml

      - name: Validate JSON
        uses: walbo/validate-json@v1.1.0
        with:
          files: action.yml
          schema: https://json.schemastore.org/github-action.json
          schema-version: draft-04
          print-valid-files: false
          fail-on-missing-schema: false
          strict: true
          allow-matching-properties: false
          allow-union-types: true

  semver:
    runs-on: ubuntu-latest
    needs: [ lint ]
    permissions:
      contents: write
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - name: Create/Update Draft release
        uses: release-drafter/release-drafter@v5
        with:
          publish: true
          prerelease: false
          config-name: configs/draft-release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
