name: Release
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    name: Release GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/release-github-actions@v6
#  default:
#    uses: cloudposse/github-actions-workflows/.github/workflows/dockerized-app-release.yml@main
#    with:
#      organization: "${{ github.event.repository.owner.login }}"
#      repository: "${{ github.event.repository.name }}"
#      registry: registry.hub.docker.com
#      version: ${{ github.event.release.tag_name }}
#    secrets:
#      docker-login: "${{ secrets.DOCKERHUB_USERNAME }}"
#      docker-password: "${{ secrets.DOCKERHUB_PASSWORD }}"
#      github-private-actions-pat: "${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}"